name: 4DAnyone
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - cuda-version=12.8
  - pytorch-gpu
  - torchvision
  - ffmpeg=*=gpl*
  - colorlog
  - einops
  - ffmpeg-python
  - fire
  - huggingface_hub
  - hydra-core
  - hydra-zen
  - imageio
  - kornia
  - numpy
  - opencv
  - pillow
  - pytorch-lightning
  - safetensors
  - scipy
  - timm
  - tqdm
  - transformers
  - typing_extensions
  - ultralytics=8.4.167
  - yacs
  - gradio=6.29.0
  - rerun-sdk=0.38.1
  - pip
  - pip:
      - av==19.0.0
      - diffsynth==2.1.8
      - triton-windows==3.8.0.post28; sys_platform == "win32"
      - lapx
      - roma
      - smplx
      - gradio-rerun==0.38.1
      - ultralytics-platform==0.1.72
